### ISSUE TITLE
Комментарий от ментора

### ISSUE THREAD

**Issue by Petergod** [rusyak/rusyak.github.io#1]
**Размещение файлов** - корректно нужно картинки чтобы были в папке с картинками, файлы стилей в папке со стилями пример корневой папки: "css (папка), img (папка), index.html"
**Визуально** - все отлично
**Разметка html кода файла index.html:** Структура и расположения тегов хорошо.Ничего лишнего. Изображение можно было взять не в тег р , а просто в `<div class="foto"> </div>`
CSS Все хорошо!
Но можно было в body обойтись без : 
`body { width: 1440px; height: 806px; border-bottom: 2px solid black; }`

Не нужно было задавать параметр height: 1440px; так, как если текста будет больше, документ не потянется и ширина также не нужно, у нас границы нужной странички заданы в .layout .
Но Визуально и по коду все хорошо!

**Comment by rusyak** [comment]
Дякую за оцінку та рекомендації. Враховані наступні рекомендації:
1) Файли, такі як фото, стилі розміщені по папкам. 
2) "Изображение можно было взять не в тег р , а просто в `<div class="foto"> </div>`" - виправлено.
3) "Но можно было в body обойтись без : `body { width: 1440px; height: 806px; border-bottom: 2px solid black; }` " - ширину і висоту задав, тому що в умовах ДЗ було вказано - "должны совпадать размеры". Нижню лінію рамки видалив.

**Comment by Petergod** [comment]
**По виправленнях**
**HTML**
- Мой контактный телефон, Мой профиль вконтакте,Мой фидбек  - потрібно брати в один параграф р. А для переносів потрібно задавати `<span>текст для переносу </span>` і в CSS задати `span {display:block;}`

**CSS**
- рекомендую в wrapper задати `padding:30px 50px;`
- для img  height: auto; можна не задавати 
- для відсутпу між рядками , потрібно задати `p,ul { line-height:20px;}` 

Як підправите , дайте знати!!!

**Comment by rusyak** [comment]
Правки враховані.

**Comment by Petergod** [comment]
**ЗАЧЕТ**
