### ISSUE TITLE
Екзамен 25

### ISSUE THREAD

**Issue by Petergod** [rusyak/rusyak.github.io#12]
- бекграунд должен растягиваться на всю ширину монитора 
- ширина контента  должна соответствовать как в макете  
- http://joxi.ru/vAWXNaeukDNDor должны быть по центру 
- http://joxi.ru/a2X4JRYFydG6O2 Должны быть в ряд
- http://joxi.ru/V2VD8ZvS0eZDVr поехал логотип , это все из-за того что задана ширина для всего контента в wrapper 
- http://joxi.ru/5mddaJnfv57Owm эти все картинки можно было сделать через псевдоклассы before/after , картинкой не нужно )

**Comment by rusyak** [comment]
Зауваження враховані.
Сприводу " http://joxi.ru/a2X4JRYFydG6O2 Должны быть в ряд ", то в одному з макетів в неправильному порядку розміщені фотки, тому я залишив все як є.

**Comment by Petergod** [comment]
**ЗАЧЕТ**
